version: '3'

services:
  consul:
    image: topaztechnology/consul:1.0.6
    hostname: consul
    restart: always
    ports:
    - 8500:8500
    volumes:
    - consul-data:/consul/data
    environment:
      LOG_LEVEL: INFO
      CONSUL_TYPE: server

  cassandra:
    image: cassandra:3.11
    hostname: cassandra
    restart: always
    ports:
    - 9042:9042
    volumes:
    - cassandra-data:/var/lib/cassandra

  redis:
    image: topaztechnology/redis:4.0.2
    hostname: redis
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis-data:/redis/data
    environment:
      LOG_LEVEL: INFO
      REDIS_TYPE: server

  monet:
    image: topaztechnology/monetdb:11.31.13
    hostname: monet
    restart: always
    ports:
    - 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: pivot-db

  topaz:
    image: topaztechnology/topaz:1.5.7
    hostname: topaz
    restart: always
    ports:
    - 9021:9021
    - 127.0.0.1:26630:26630
    - 26634:26634
    - 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-shared:/opt/topaz/tmp
    environment:
      EXTERNAL_HOSTNAME: localhost
      LOG_LEVEL: DEBUG
      BACKEND_DB_TYPE: cassandra
      BACKEND_TICK_DB_TYPE: redis
      PIVOT_DB_TYPE: monet
      MONET_BULK_LOAD_DIR: /opt/topaz/tmp
      CONSUL_URL: http://consul:8500
      ROOT_PASSWORD: # Set first time only
    depends_on:
    - consul
    - cassandra
    - redis
    - monet

volumes:
  consul-data:
  cassandra-data:
  redis-data:
  monet-data:
  topaz-data:
  topaz-shared:
  topaz-conf:
    external: true
