version: '3'

services:
  cassandra:
    image: cassandra:3.11
    hostname: cassandra
    restart: always
    # Uncomment to expose Cassandra externally
    #ports:
    #- 9042:9042
    volumes:
    - cassandra-data:/var/lib/cassandra

  redis:
    image: topaztechnology/redis:4.0.2
    hostname: redis
    restart: always
    # Uncomment to expose Redis externally
    #ports:
    #- 6379:6379
    volumes:
    - redis-data:/redis/data
    environment:
      LOG_LEVEL: INFO
      REDIS_TYPE: server

  monet:
    image: topaztechnology/monetdb:11.31.13
    hostname: monet
    restart: always
    # Uncomment to expose Monet externally
    #ports:
    #- 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: pivot-db

  topaz:
    image: topaztechnology/topaz:latest
    hostname: topaz
    restart: always
    ports:
    - 9021:9021    # Getdown port
    - 26634:26634  # Topaz server port
    # Uncomment to expost REPL port locally
    #- 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-shared:/opt/topaz/tmp
    environment:
      EXTERNAL_HOSTNAME: localhost
      LOG_LEVEL: DEBUG
      BACKEND_DB_TYPE: cassandra
      BACKEND_TICK_DB_TYPE: redis
      PIVOT_DB_TYPE: monet
      MONET_BULK_LOAD_DIR: /opt/topaz/tmp
      # Set first time only using bin/create-password-hash.sh. Remember to quote and replace $ with $$
      # This example has a password of "root" and must be changed
      ROOT_PASSWORD_HASH: "$$2a$$12$$FMN3DQ5DeF06gLw/yb3WsegCTSExXb34g6mdLp8ctD6GaKK80VvpO"
      # Set this initially here or in config and never change.
      # This example hashing pepper must be changed
      PASSWORD_HASHING_PEPPER: "pepper"
    depends_on:
    - consul
    - cassandra
    - redis
    - monet

volumes:
  consul-data:
  cassandra-data:
  redis-data:
  monet-data:
  topaz-data:
  topaz-shared:
  topaz-conf:
    external: true
