version: '3'

services:
  elk:
    image: topaztechnology/elk:660
    hostname: elk
    restart: always
    ports:
    - 5140:5140/udp
    - 5601:5601
    volumes:
    - elk-data:/var/lib/elasticsearch

volumes:
  elk-data:
