version: '3'

services:
  postgres:
    image: postgres:10.2-alpine
    hostname: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: topaz
      POSTGRES_DB: topaz-main

  redis:
    image: topaztechnology/redis:4.0.2
    hostname: redis
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis-data:/redis/data
    environment:
      LOG_LEVEL: INFO
      REDIS_TYPE: server

  monet:
    image: topaztechnology/monetdb:11.31.13
    hostname: monet
    restart: always
    ports:
    - 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: topaz-pivot

  topaz:
    image: topaztechnology/topaz:1.5.8
    hostname: topaz
    restart: always
    ports:
    - 9021:9021
    - 127.0.0.1:26630:26630
    - 26634:26634
    - 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-log:/opt/topaz/log
    - topaz-shared:/opt/topaz/tmp
    environment:
      EXTERNAL_HOSTNAME: localhost
      LOG_LEVEL: DEBUG
      BACKEND_DB_TYPE: postgres
      BACKEND_TICK_DB_TYPE: redis
      PIVOT_DB_TYPE: monet
      MONET_BULK_LOAD_DIR: /opt/topaz/tmp
      JAVA_DEBUG: 1
      JAVA_DEBUG_PORT: 26630
      ROOT_PASSWORD_HASH: # Set first time only using bin/create-password-hash.sh. Remember to quote and replace $ with $$
      PASSWORD_HASHING_PEPPER: # Set this initially and never change
    depends_on:
    - postgres
    - redis
    - monet

volumes:
  postgres-data:
  redis-data:
  monet-data:
  topaz-data:
  topaz-log:
  topaz-shared:
  topaz-conf:
    external: true
